--- #YAML:1.0
name:                threads
version:             1.71
abstract:            Perl interpreter-based threads
license:             perl
author:              
    - Artur Bergman, Jerry D. Hedden <jdhedden AT cpan DOT org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    Config:                        0
    ExtUtils::testlib:             0
    Hash::Util:                    0
    IO::File:                      0
    overload:                      0
    strict:                        0
    Test::More:                    0
    warnings:                      0
    XSLoader:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
